# Changes here will be overwritten by Copier
_commit: 1.2.4
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2024'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: true
insiders_email: insiders@pawamoy.fr
insiders_repository_name: mkdocs-pygments
project_description: Highlighting themes for code blocks.
project_name: MkDocs Pygments
public_release: false
python_package_command_line_name: ''
python_package_distribution_name: mkdocs-pygments
python_package_import_name: mkdocs_pygments
repository_name: mkdocs-pygments
repository_namespace: pawamoy
repository_provider: github.com

